# Migración que agrega el campo mac_address al modelo Device.
# Permite asociar una dirección MAC a cada dispositivo para validación
# cruzada de identidad en el subscriber MQTT.
# Generated by Django 6.0.5 on 2026-05-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
    ]
