# Migración que crea el modelo UserProfile para asignación de roles.
# Implementa el sistema RBAC (Role-Based Access Control) sobre el
# modelo User personalizado.
# Generated by Django 5.0.14 on 2026-05-28 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_device_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='viewer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
